### ISSUE TITLE
しばらく運用するとスレッド一覧情報取得ができなくなる

### ISSUE THREAD

**Issue by Hiroyuki-Nagata** [windymelt/p2p2ch#5]
タイトルの通り、ログを貼り付けます
https://gist.github.com/Hiroyuki-Nagata/7888399

Caused by: java.util.NoSuchElementException: None.get
とあるので、すでになくなったノードを参照しているとかですかねえ…？

p2p2ch起動から問題発生まで約７時間ぐらいです。
エラーログは、スレッド一覧情報を取得した際に発生します。

**Comment by Hiroyuki-Nagata** [comment]
最近これ起きてないです

**Comment by hangingman** [comment]
問題が起きていないのでクローズします
